meta_product_name: "DIWYH"
meta_title: "DIWYH - Reconnect with your hands"
meta_description: "DIWYH is the place to meet craftsman for people who wants to learn new manual skills"
meta_image: "og_craftman_avatar.png"                       # should exist in `app/assets/images/`
